<?php

return [
    "flat"   => "F",
    "house_villa"   => "V",
    "penthouse"   => "P",
    "studio"   => "S",
    "residential_land_plot"   => "L",
    "residential_building"   => "B",
    "office"=> "O",
    "shop_showroom"=> "S",
    "warehouse_godown"=> "W",
    "mall"=> "M",
    "commercial_land_plot"=> "L",
    "commercial_building"=> "B",
    "industrial_building"=> "B",
    "industrial_shed"=> "S",
    "p&m" =>"P",
    "industrial_land_plot"=> "L",
    "industrial_gala"=> "G",
    "farm_house"=> "F",
    "agricultural_land_plot"=> "L",
    "stock"=> "S",
    "others"=> "O",
    "vehicles"=> "V",
];
