<?php

use Illuminate\Database\Seeder;
use App\Models\LocationMaster;

class LocationMasterTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $arr = [
            ["city" => "Adilabad", "state" => "Andhra Pradesh"],
            ["city" => "Anantapur", "state" => "Andhra Pradesh"],
            ["city" => "Chittoor", "state" => "Andhra Pradesh"],
            ["city" => "East Godavari", "state" => "Andhra Pradesh"],
            ["city" => "Guntur", "state" => "Andhra Pradesh"],
            ["city" => "Hyderabad", "state" => "Andhra Pradesh"],
            ["city" => "YSR district", "state" => "Andhra Pradesh"],
            ["city" => "Karimnagar", "state" => "Andhra Pradesh"],
            ["city" => "Khammam", "state" => "Andhra Pradesh"],
            ["city" => "Krishna (N T R District)", "state" => "Andhra Pradesh"],
            ["city" => "Kurnool", "state" => "Andhra Pradesh"],
            ["city" => "Mahbubnagar", "state" => "Andhra Pradesh"],
            ["city" => "Medak", "state" => "Andhra Pradesh"],
            ["city" => "Nalgonda", "state" => "Andhra Pradesh"],
            ["city" => "Nellore", "state" => "Andhra Pradesh"],
            ["city" => "Nizamabad", "state" => "Andhra Pradesh"],
            ["city" => "Prakasam", "state" => "Andhra Pradesh"],
            ["city" => "Rangareddi", "state" => "Andhra Pradesh"],
            ["city" => "Srikakulam", "state" => "Andhra Pradesh"],
            ["city" => "Vishakhapatnam", "state" => "Andhra Pradesh"],
            ["city" => "Vizianagaram", "state" => "Andhra Pradesh"],
            ["city" => "Warangal", "state" => "Andhra Pradesh"],
            ["city" => "West Godavari", "state" => "Andhra Pradesh"],
            ["city" => "Anjaw", "state" => "Arunachal Pradesh"],
            ["city" => "Changlang", "state" => "Arunachal Pradesh"],
            ["city" => "East Kameng", "state" => "Arunachal Pradesh"],
            ["city" => "East Siang", "state" => "Arunachal Pradesh"],
            ["city" => "Lohit", "state" => "Arunachal Pradesh"],
            ["city" => "Lower Subansiri", "state" => "Arunachal Pradesh"],
            ["city" => "Papum Pare", "state" => "Arunachal Pradesh"],
            ["city" => "Tawang", "state" => "Arunachal Pradesh"],
            ["city" => "Tirap", "state" => "Arunachal Pradesh"],
            ["city" => "Dibang Valley", "state" => "Arunachal Pradesh"],
            ["city" => "Upper Siang", "state" => "Arunachal Pradesh"],
            ["city" => "Upper Subansiri", "state" => "Arunachal Pradesh"],
            ["city" => "West Kameng", "state" => "Arunachal Pradesh"],
            ["city" => "West Siang", "state" => "Arunachal Pradesh"],
            ["city" => "Barpeta", "state" => "Assam"],
            ["city" => "Bongaigaon", "state" => "Assam"],
            ["city" => "Cachar", "state" => "Assam"],
            ["city" => "Darrang", "state" => "Assam"],
            ["city" => "Dhemaji", "state" => "Assam"],
            ["city" => "Dhubri", "state" => "Assam"],
            ["city" => "Dibrugarh", "state" => "Assam"],
            ["city" => "Goalpara", "state" => "Assam"],
            ["city" => "Golaghat", "state" => "Assam"],
            ["city" => "Hailakandi", "state" => "Assam"],
            ["city" => "Jorhat", "state" => "Assam"],
            ["city" => "Karbi Anglong", "state" => "Assam"],
            ["city" => "Karimganj", "state" => "Assam"],
            ["city" => "Kokrajhar", "state" => "Assam"],
            ["city" => "Lakhimpur", "state" => "Assam"],
            ["city" => "Marigaon", "state" => "Assam"],
            ["city" => "Nagaon", "state" => "Assam"],
            ["city" => "Nalbari", "state" => "Assam"],
            ["city" => "Dima Hasao", "state" => "Assam"],
            ["city" => "Sibsagar", "state" => "Assam"],
            ["city" => "Sonitpur", "state" => "Assam"],
            ["city" => "Tinsukia", "state" => "Assam"],
            ["city" => "Araria", "state" => "Bihar"],
            ["city" => "Arwal", "state" => "Bihar"],
            ["city" => "Aurangabad", "state" => "Bihar"],
            ["city" => "Banka", "state" => "Bihar"],
            ["city" => "Begusarai", "state" => "Bihar"],
            ["city" => "Bhagalpur", "state" => "Bihar"],
            ["city" => "Bhojpur", "state" => "Bihar"],
            ["city" => "Buxar", "state" => "Bihar"],
            ["city" => "Darbhanga", "state" => "Bihar"],
            ["city" => "East Champaran", "state" => "Bihar"],
            ["city" => "Gaya", "state" => "Bihar"],
            ["city" => "Gopalganj", "state" => "Bihar"],
            ["city" => "Jamui", "state" => "Bihar"],
            ["city" => "Jehanabad", "state" => "Bihar"],
            ["city" => "Khagaria", "state" => "Bihar"],
            ["city" => "Kishanganj", "state" => "Bihar"],
            ["city" => "Kaimur", "state" => "Bihar"],
            ["city" => "Katihar", "state" => "Bihar"],
            ["city" => "Lakhisarai", "state" => "Bihar"],
            ["city" => "Madhubani", "state" => "Bihar"],
            ["city" => "Munger", "state" => "Bihar"],
            ["city" => "Madhepura", "state" => "Bihar"],
            ["city" => "Muzaffarpur", "state" => "Bihar"],
            ["city" => "Nalanda", "state" => "Bihar"],
            ["city" => "Nawada", "state" => "Bihar"],
            ["city" => "Patna", "state" => "Bihar"],
            ["city" => "Purnia", "state" => "Bihar"],
            ["city" => "Rohtas", "state" => "Bihar"],
            ["city" => "Saharsa", "state" => "Bihar"],
            ["city" => "Samastipur", "state" => "Bihar"],
            ["city" => "Sheohar", "state" => "Bihar"],
            ["city" => "Sheikhpura", "state" => "Bihar"],
            ["city" => "Saran", "state" => "Bihar"],
            ["city" => "Sitamarhi", "state" => "Bihar"],
            ["city" => "Supaul", "state" => "Bihar"],
            ["city" => "Siwan", "state" => "Bihar"],
            ["city" => "Vaishali(Akshay)", "state" => "Bihar"],
            ["city" => "West Champaran", "state" => "Bihar"],
            ["city" => "Bastar", "state" => "Chhattisgarh"],
            ["city" => "Bijapur", "state" => "Chhattisgarh"],
            ["city" => "Bilaspur", "state" => "Chhattisgarh"],
            ["city" => "Dantewada", "state" => "Chhattisgarh"],
            ["city" => "Dhamtari", "state" => "Chhattisgarh"],
            ["city" => "Durg", "state" => "Chhattisgarh"],
            ["city" => "Jashpur", "state" => "Chhattisgarh"],
            ["city" => "Janjgir-Champa", "state" => "Chhattisgarh"],
            ["city" => "Korba", "state" => "Chhattisgarh"],
            ["city" => "Koriya", "state" => "Chhattisgarh"],
            ["city" => "Kanker", "state" => "Chhattisgarh"],
            ["city" => "Kawardha", "state" => "Chhattisgarh"],
            ["city" => "Mahasamund", "state" => "Chhattisgarh"],
            ["city" => "Narayanpur", "state" => "Chhattisgarh"],
            ["city" => "Raigarh", "state" => "Chhattisgarh"],
            ["city" => "Rajnandgaon", "state" => "Chhattisgarh"],
            ["city" => "Raipur", "state" => "Chhattisgarh"],
            ["city" => "Surajpur", "state" => "Chhattisgarh"],
            ["city" => "Central Delhi", "state" => "Delhi"],
            ["city" => "East Delhi", "state" => "Delhi"],
            ["city" => "New Delhi", "state" => "Delhi"],
            ["city" => "North Delhi", "state" => "Delhi"],
            ["city" => "North East Delhi", "state" => "Delhi"],
            ["city" => "North West Delhi", "state" => "Delhi"],
            ["city" => "South Delhi", "state" => "Delhi"],
            ["city" => "South West Delhi", "state" => "Delhi"],
            ["city" => "West Delhi", "state" => "Delhi"],
            ["city" => "North Goa", "state" => "Goa"],
            ["city" => "South Goa", "state" => "Goa"],
            ["city" => "Ahmedabad", "state" => "Gujarat"],
            ["city" => "Amreli District", "state" => "Gujarat"],
            ["city" => "Anand", "state" => "Gujarat"],
            ["city" => "Banaskantha", "state" => "Gujarat"],
            ["city" => "Bharuch", "state" => "Gujarat"],
            ["city" => "Bhavnagar", "state" => "Gujarat"],
            ["city" => "Dahod", "state" => "Gujarat"],
            ["city" => "The Dangs", "state" => "Gujarat"],
            ["city" => "Gandhinagar", "state" => "Gujarat"],
            ["city" => "Jamnagar", "state" => "Gujarat"],
            ["city" => "Junagadh", "state" => "Gujarat"],
            ["city" => "Kutch", "state" => "Gujarat"],
            ["city" => "Kheda", "state" => "Gujarat"],
            ["city" => "Mehsana", "state" => "Gujarat"],
            ["city" => "Narmada", "state" => "Gujarat"],
            ["city" => "Navsari", "state" => "Gujarat"],
            ["city" => "Patan", "state" => "Gujarat"],
            ["city" => "Panchmahal", "state" => "Gujarat"],
            ["city" => "Porbandar", "state" => "Gujarat"],
            ["city" => "Rajkot", "state" => "Gujarat"],
            ["city" => "Sabarkantha", "state" => "Gujarat"],
            ["city" => "Surendranagar", "state" => "Gujarat"],
            ["city" => "Surat", "state" => "Gujarat"],
            ["city" => "Vadodara", "state" => "Gujarat"],
            ["city" => "Valsad", "state" => "Gujarat"],
            ["city" => "Ambala", "state" => "Haryana"],
            ["city" => "Bhiwani", "state" => "Haryana"],
            ["city" => "Faridabad", "state" => "Haryana"],
            ["city" => "Fatehabad", "state" => "Haryana"],
            ["city" => "Gurgaon", "state" => "Haryana"],
            ["city" => "Hissar", "state" => "Haryana"],
            ["city" => "Jhajjar", "state" => "Haryana"],
            ["city" => "Jind", "state" => "Haryana"],
            ["city" => "Karnal", "state" => "Haryana"],
            ["city" => "Kaithal", "state" => "Haryana"],
            ["city" => "Kurukshetra", "state" => "Haryana"],
            ["city" => "Mahendragarh", "state" => "Haryana"],
            ["city" => "Mewat", "state" => "Haryana"],
            ["city" => "Panchkula", "state" => "Haryana"],
            ["city" => "Panipat", "state" => "Haryana"],
            ["city" => "Rewari", "state" => "Haryana"],
            ["city" => "Rohtak", "state" => "Haryana"],
            ["city" => "Sirsa", "state" => "Haryana"],
            ["city" => "Sonepat", "state" => "Haryana"],
            ["city" => "Yamuna Nagar", "state" => "Haryana"],
            ["city" => "Palwal", "state" => "Haryana"],
            ["city" => "Bilaspur", "state" => "Himachal Pradesh"],
            ["city" => "Chamba", "state" => "Himachal Pradesh"],
            ["city" => "Hamirpur", "state" => "Himachal Pradesh"],
            ["city" => "Kangra", "state" => "Himachal Pradesh"],
            ["city" => "Kinnaur", "state" => "Himachal Pradesh"],
            ["city" => "Kulu", "state" => "Himachal Pradesh"],
            ["city" => "Lahaul and Spiti", "state" => "Himachal Pradesh"],
            ["city" => "Mandi", "state" => "Himachal Pradesh"],
            ["city" => "Shimla", "state" => "Himachal Pradesh"],
            ["city" => "Sirmaur", "state" => "Himachal Pradesh"],
            ["city" => "Solan", "state" => "Himachal Pradesh"],
            ["city" => "Una", "state" => "Himachal Pradesh"],
            ["city" => "Anantnag", "state" => "Jammu and Kashmir"],
            ["city" => "Badgam", "state" => "Jammu and Kashmir"],
            ["city" => "Bandipore", "state" => "Jammu and Kashmir"],
            ["city" => "Baramula", "state" => "Jammu and Kashmir"],
            ["city" => "Doda", "state" => "Jammu and Kashmir"],
            ["city" => "Ganderbal", "state" => "Jammu and Kashmir"],
            ["city" => "Jammu", "state" => "Jammu and Kashmir"],
            ["city" => "Kargil", "state" => "Jammu and Kashmir"],
            ["city" => "Kathua", "state" => "Jammu and Kashmir"],
            ["city" => "Kishtwar", "state" => "Jammu and Kashmir"],
            ["city" => "Kupwara", "state" => "Jammu and Kashmir"],
            ["city" => "Kulgam", "state" => "Jammu and Kashmir"],
            ["city" => "Leh", "state" => "Jammu and Kashmir"],
            ["city" => "Poonch", "state" => "Jammu and Kashmir"],
            ["city" => "Pulwama", "state" => "Jammu and Kashmir"],
            ["city" => "Rajauri", "state" => "Jammu and Kashmir"],
            ["city" => "Ramban", "state" => "Jammu and Kashmir"],
            ["city" => "Reasi", "state" => "Jammu and Kashmir"],
            ["city" => "Samba", "state" => "Jammu and Kashmir"],
            ["city" => "Shopian", "state" => "Jammu and Kashmir"],
            ["city" => "Srinagar", "state" => "Jammu and Kashmir"],
            ["city" => "Udhampur district", "state" => "Jammu and Kashmir"],
            ["city" => "Bokaro", "state" => "Jharkhand"],
            ["city" => "Chatra", "state" => "Jharkhand"],
            ["city" => "Deoghar", "state" => "Jharkhand"],
            ["city" => "Dhanbad", "state" => "Jharkhand"],
            ["city" => "Dumka", "state" => "Jharkhand"],
            ["city" => "East Singhbhum", "state" => "Jharkhand"],
            ["city" => "Garhwa", "state" => "Jharkhand"],
            ["city" => "Giridih", "state" => "Jharkhand"],
            ["city" => "Godda", "state" => "Jharkhand"],
            ["city" => "Gumla", "state" => "Jharkhand"],
            ["city" => "Hazaribag", "state" => "Jharkhand"],
            ["city" => "Koderma", "state" => "Jharkhand"],
            ["city" => "Lohardaga", "state" => "Jharkhand"],
            ["city" => "Pakur", "state" => "Jharkhand"],
            ["city" => "Palamu", "state" => "Jharkhand"],
            ["city" => "Ranchi", "state" => "Jharkhand"],
            ["city" => "Sahibganj", "state" => "Jharkhand"],
            ["city" => "Seraikela-Kharsawan", "state" => "JharkhanD"],
            ["city" => "West Singhbhum", "state" => "Jharkhand"],
            ["city" => "Ramgarh", "state" => "Jharkhand"],
            ["city" => "Bidar", "state" => "Karnataka"],
            ["city" => "Belgaum", "state" => "Karnataka"],
            ["city" => "Bijapur", "state" => "Karnataka"],
            ["city" => "Bagalkot", "state" => "Karnataka"],
            ["city" => "Bellary", "state" => "Karnataka"],
            ["city" => "Bangalore Rural District", "state" => "Karnataka"],
            ["city" => "Bangalore Urban district", "state" => "Karnataka"],
            ["city" => "Chamarajnagar", "state" => "Karnataka"],
            ["city" => "Chikkodi", "state" => "Karnataka"],
            ["city" => "Chikmagalur", "state" => "Karnataka"],
            ["city" => "Chitradurga", "state" => "Karnataka"],
            ["city" => "Davanagere", "state" => "Karnataka"],
            ["city" => "Dharwad", "state" => "Karnataka"],
            ["city" => "Dakshina Kannada", "state" => "Karnataka"],
            ["city" => "Gadag", "state" => "Karnataka"],
            ["city" => "Gulbarga", "state" => "Karnataka"],
            ["city" => "Hassan", "state" => "Karnataka"],
            ["city" => "Haveri District", "state" => "Karnataka"],
            ["city" => "Kodagu", "state" => "Karnataka"],
            ["city" => "Kolar", "state" => "Karnataka"],
            ["city" => "Koppal", "state" => "Karnataka"],
            ["city" => "Mandya", "state" => "Karnataka"],
            ["city" => "Mysore", "state" => "Karnataka"],
            ["city" => "Raichur", "state" => "Karnataka"],
            ["city" => "Shimoga", "state" => "Karnataka"],
            ["city" => "Tumkur", "state" => "Karnataka"],
            ["city" => "Udupi", "state" => "Karnataka"],
            ["city" => "Uttara Kannada", "state" => "Karnataka"],
            ["city" => "Ramanagara", "state" => "Karnataka"],
            ["city" => "Chikballapur", "state" => "Karnataka"],
            ["city" => "Yadgir", "state" => "Karnataka"],
            ["city" => "Alappuzha", "state" => "Kerala"],
            ["city" => "Ernakulam", "state" => "Kerala"],
            ["city" => "Idukki", "state" => "Kerala"],
            ["city" => "Kollam", "state" => "Kerala"],
            ["city" => "Kannur", "state" => "Kerala"],
            ["city" => "Kasaragod", "state" => "Kerala"],
            ["city" => "Kottayam", "state" => "Kerala"],
            ["city" => "Kozhikode", "state" => "Kerala"],
            ["city" => "Malappuram", "state" => "Kerala"],
            ["city" => "Palakkad", "state" => "Kerala"],
            ["city" => "Pathanamthitta", "state" => "Kerala"],
            ["city" => "Thrissur", "state" => "Kerala"],
            ["city" => "Thiruvananthapuram", "state" => "Kerala"],
            ["city" => "Wayanad", "state" => "Kerala"],
            ["city" => "Alirajpur", "state" => "Madhya Pradesh"],
            ["city" => "Anuppur", "state" => "Madhya Pradesh"],
            ["city" => "Ashok Nagar", "state" => "Madhya Pradesh"],
            ["city" => "Balaghat", "state" => "Madhya Pradesh"],
            ["city" => "Barwani", "state" => "Madhya Pradesh"],
            ["city" => "Betul", "state" => "Madhya Pradesh"],
            ["city" => "Bhind", "state" => "Madhya Pradesh"],
            ["city" => "Bhopal", "state" => "Madhya Pradesh"],
            ["city" => "Burhanpur", "state" => "Madhya Pradesh"],
            ["city" => "Chhatarpur", "state" => "Madhya Pradesh"],
            ["city" => "Chhindwara", "state" => "Madhya Pradesh"],
            ["city" => "Damoh", "state" => "Madhya Pradesh"],
            ["city" => "Datia", "state" => "Madhya Pradesh"],
            ["city" => "Dewas", "state" => "Madhya Pradesh"],
            ["city" => "Dhar", "state" => "Madhya Pradesh"],
            ["city" => "Dindori", "state" => "Madhya Pradesh"],
            ["city" => "Guna", "state" => "Madhya Pradesh"],
            ["city" => "Gwalior", "state" => "Madhya Pradesh"],
            ["city" => "Harda", "state" => "Madhya Pradesh"],
            ["city" => "Hoshangabad", "state" => "Madhya Pradesh"],
            ["city" => "Indore", "state" => "Madhya Pradesh"],
            ["city" => "Jabalpur", "state" => "Madhya Pradesh"],
            ["city" => "Jhabua", "state" => "Madhya Pradesh"],
            ["city" => "Katni", "state" => "Madhya Pradesh"],
            ["city" => "Khandwa (East Nimar)", "state" => "Madhya Pradesh"],
            ["city" => "Khargone (West Nimar)", "state" => "Madhya Pradesh"],
            ["city" => "Mandla", "state" => "Madhya Pradesh"],
            ["city" => "Mandsaur", "state" => "Madhya Pradesh"],
            ["city" => "Morena", "state" => "Madhya Pradesh"],
            ["city" => "Narsinghpur", "state" => "Madhya Pradesh"],
            ["city" => "Neemuch", "state" => "Madhya Pradesh"],
            ["city" => "Panna", "state" => "Madhya Pradesh"],
            ["city" => "Rewa", "state" => "Madhya Pradesh"],
            ["city" => "Rajgarh", "state" => "Madhya Pradesh"],
            ["city" => "Ratlam", "state" => "Madhya Pradesh"],
            ["city" => "Raisen", "state" => "Madhya Pradesh"],
            ["city" => "Sagar", "state" => "Madhya Pradesh"],
            ["city" => "Satna", "state" => "Madhya Pradesh"],
            ["city" => "Sehore", "state" => "Madhya Pradesh"],
            ["city" => "Seoni", "state" => "Madhya Pradesh"],
            ["city" => "Shahdol", "state" => "Madhya Pradesh"],
            ["city" => "Shajapur", "state" => "Madhya Pradesh"],
            ["city" => "Sheopur", "state" => "Madhya Pradesh"],
            ["city" => "Shivpuri", "state" => "Madhya Pradesh"],
            ["city" => "Sidhi", "state" => "Madhya Pradesh"],
            ["city" => "Singrauli", "state" => "Madhya Pradesh"],
            ["city" => "Tikamgarh", "state" => "Madhya Pradesh"],
            ["city" => "Ujjain", "state" => "Madhya Pradesh"],
            ["city" => "Umaria", "state" => "Madhya Pradesh"],
            ["city" => "Vidisha", "state" => "Madhya Pradesh"],
            ["city" => "Ahmednagar", "state" => "Maharashtra"],
            ["city" => "Akola", "state" => "Maharashtra"],
            ["city" => "Amravati", "state" => "Maharashtra"],
            ["city" => "Aurangabad", "state" => "Maharashtra"],
            ["city" => "Bhandara", "state" => "Maharashtra"],
            ["city" => "Beed", "state" => "Maharashtra"],
            ["city" => "Buldhana", "state" => "Maharashtra"],
            ["city" => "Chandrapur", "state" => "Maharashtra"],
            ["city" => "Dhule", "state" => "Maharashtra"],
            ["city" => "Gadchiroli", "state" => "Maharashtra"],
            ["city" => "Gondia", "state" => "Maharashtra"],
            ["city" => "Hingoli", "state" => "Maharashtra"],
            ["city" => "Jalgaon", "state" => "Maharashtra"],
            ["city" => "Jalna", "state" => "Maharashtra"],
            ["city" => "Kolhapur", "state" => "Maharashtra"],
            ["city" => "Latur", "state" => "Maharashtra"],
            ["city" => "Mumbai", "state" => "Maharashtra"],
            ["city" => "Nandurbar", "state" => "Maharashtra"],
            ["city" => "Nanded", "state" => "Maharashtra"],
            ["city" => "Nagpur", "state" => "Maharashtra"],
            ["city" => "Nashik", "state" => "Maharashtra"],
            ["city" => "Osmanabad", "state" => "Maharashtra"],
            ["city" => "Parbhani", "state" => "Maharashtra"],
            ["city" => "Pune", "state" => "Maharashtra"],
            ["city" => "Raigad", "state" => "Maharashtra"],
            ["city" => "Ratnagiri", "state" => "Maharashtra"],
            ["city" => "Sindhudurg", "state" => "Maharashtra"],
            ["city" => "Sangli", "state" => "Maharashtra"],
            ["city" => "Solapur", "state" => "Maharashtra"],
            ["city" => "Satara", "state" => "Maharashtra"],
            ["city" => "Thane", "state" => "Maharashtra"],
            ["city" => "Wardha", "state" => "Maharashtra"],
            ["city" => "Washim", "state" => "Maharashtra"],
            ["city" => "Yavatmal", "state" => "Maharashtra"],
            ["city" => "Bishnupur", "state" => "Manipur"],
            ["city" => "Churachandpur", "state" => "Manipur"],
            ["city" => "Chandel", "state" => "Manipur"],
            ["city" => "Imphal East", "state" => "Manipur"],
            ["city" => "Senapati", "state" => "Manipur"],
            ["city" => "Tamenglong", "state" => "Manipur"],
            ["city" => "Thoubal", "state" => "Manipur"],
            ["city" => "Ukhrul", "state" => "Manipur"],
            ["city" => "Imphal West", "state" => "Manipur"],
            ["city" => "East Garo Hills", "state" => "Meghalaya"],
            ["city" => "East Khasi Hills", "state" => "Meghalaya"],
            ["city" => "Jaintia Hills", "state" => "Meghalaya"],
            ["city" => "Ri Bhoi", "state" => "Meghalaya"],
            ["city" => "South Garo Hills", "state" => "Meghalaya"],
            ["city" => "West Garo Hills", "state" => "Meghalaya"],
            ["city" => "West Khasi Hills", "state" => "Meghalaya"],
            ["city" => "Aizawl", "state" => "Mizoram"],
            ["city" => "Champhai", "state" => "Mizoram"],
            ["city" => "Kolasib", "state" => "Mizoram"],
            ["city" => "Lawngtlai", "state" => "Mizoram"],
            ["city" => "Lunglei", "state" => "Mizoram"],
            ["city" => "Mamit", "state" => "Mizoram"],
            ["city" => "Saiha", "state" => "Mizoram"],
            ["city" => "Serchhip", "state" => "Mizoram"],
            ["city" => "Dimapur", "state" => "Nagaland"],
            ["city" => "Kohima", "state" => "Nagaland"],
            ["city" => "Mokokchung", "state" => "Nagaland"],
            ["city" => "Mon", "state" => "Nagaland"],
            ["city" => "Phek", "state" => "Nagaland"],
            ["city" => "Tuensang", "state" => "Nagaland"],
            ["city" => "Wokha", "state" => "Nagaland"],
            ["city" => "Zunheboto", "state" => "Nagaland"],
            ["city" => "Angul", "state" => "Orissa"],
            ["city" => "Boudh (Bauda)", "state" => "Orissa"],
            ["city" => "Bhadrak", "state" => "Orissa"],
            ["city" => "Balangir", "state" => "Orissa"],
            ["city" => "Bargarh (Baragarh)", "state" => "Orissa"],
            ["city" => "Balasore", "state" => "Orissa"],
            ["city" => "Cuttack", "state" => "Orissa"],
            ["city" => "Debagarh (Deogarh)", "state" => "Orissa"],
            ["city" => "Dhenkanal", "state" => "Orissa"],
            ["city" => "Ganjam", "state" => "Orissa"],
            ["city" => "Gajapati", "state" => "Orissa"],
            ["city" => "Jharsuguda", "state" => "Orissa"],
            ["city" => "Jajpur", "state" => "Orissa"],
            ["city" => "Jagatsinghpur", "state" => "Orissa"],
            ["city" => "Khordha", "state" => "Orissa"],
            ["city" => "Kendujhar (Keonjhar)", "state" => "Orissa"],
            ["city" => "Kalahandi", "state" => "Orissa"],
            ["city" => "Kandhamal", "state" => "Orissa"],
            ["city" => "Koraput", "state" => "Orissa"],
            ["city" => "Kendrapara", "state" => "Orissa"],
            ["city" => "Malkangiri", "state" => "Orissa"],
            ["city" => "Mayurbhanj", "state" => "Orissa"],
            ["city" => "Nabarangpur", "state" => "Orissa"],
            ["city" => "Nuapada", "state" => "Orissa"],
            ["city" => "Nayagarh", "state" => "Orissa"],
            ["city" => "Puri", "state" => "Orissa"],
            ["city" => "Rayagada", "state" => "Orissa"],
            ["city" => "Sambalpur", "state" => "Orissa"],
            ["city" => "Subarnapur (Sonepur)", "state" => "Orissa"],
            ["city" => "Sundargarh (Sundergarh)", "state" => "Orissa"],
            ["city" => "Karaikal", "state" => "Pondicherry (Puducherry)"],
            ["city" => "Mahe", "state" => "Pondicherry (Puducherry)"],
            ["city" => "Pondicherry", "state" => "Pondicherry (Puducherry)"],
            ["city" => "Yanam", "state" => "Pondicherry (Puducherry)"],
            ["city" => "Amritsar", "state" => "Punjab"],
            ["city" => "Barnala", "state" => "Punjab"],
            ["city" => "Bathinda", "state" => "Punjab"],
            ["city" => "Firozpur", "state" => "Punjab"],
            ["city" => "Faridkot", "state" => "Punjab"],
            ["city" => "Fatehgarh Sahib", "state" => "Punjab"],
            ["city" => "Fazilka district", "state" => "Punjab"],
            ["city" => "Gurdaspur", "state" => "Punjab"],
            ["city" => "Hoshiarpur", "state" => "Punjab"],
            ["city" => "Jalandhar", "state" => "Punjab"],
            ["city" => "Kapurthala", "state" => "Punjab"],
            ["city" => "Ludhiana", "state" => "Punjab"],
            ["city" => "Mansa", "state" => "Punjab"],
            ["city" => "Moga", "state" => "Punjab"],
            ["city" => "Mukatsar", "state" => "Punjab"],
            ["city" => "Pathankot", "state" => "Punjab"],
            ["city" => "Patiala", "state" => "Punjab"],
            ["city" => "Rupnagar", "state" => "Punjab"],
            ["city" => "Sahibzada Ajit Singh Nagar", "state" => "Punjab"],
            ["city" => "Sangrur", "state" => "Punjab"],
            ["city" => "Shahid Bhagat Singh Nagar", "state" => "Punjab"],
            ["city" => "Tarn Taran", "state" => "Punjab"],
            ["city" => "Ajmer", "state" => "Rajasthan"],
            ["city" => "Alwar", "state" => "Rajasthan"],
            ["city" => "Bikaner", "state" => "Rajasthan"],
            ["city" => "Barmer", "state" => "Rajasthan"],
            ["city" => "Banswara", "state" => "Rajasthan"],
            ["city" => "Bharatpur", "state" => "Rajasthan"],
            ["city" => "Baran", "state" => "Rajasthan"],
            ["city" => "Bundi", "state" => "Rajasthan"],
            ["city" => "Bhilwara", "state" => "Rajasthan"],
            ["city" => "Churu", "state" => "Rajasthan"],
            ["city" => "Chittorgarh", "state" => "Rajasthan"],
            ["city" => "Dausa", "state" => "Rajasthan"],
            ["city" => "Dholpur", "state" => "Rajasthan"],
            ["city" => "Dungapur", "state" => "Rajasthan"],
            ["city" => "Ganganagar", "state" => "Rajasthan"],
            ["city" => "Hanumangarh", "state" => "Rajasthan"],
            ["city" => "Jhunjhunu", "state" => "Rajasthan"],
            ["city" => "Jalore", "state" => "Rajasthan"],
            ["city" => "Jodhpur", "state" => "Rajasthan"],
            ["city" => "Jaipur", "state" => "Rajasthan"],
            ["city" => "Jaisalmer", "state" => "Rajasthan"],
            ["city" => "Jhalawar", "state" => "Rajasthan"],
            ["city" => "Karauli", "state" => "Rajasthan"],
            ["city" => "Kota", "state" => "Rajasthan"],
            ["city" => "Nagaur", "state" => "Rajasthan"],
            ["city" => "Pali", "state" => "Rajasthan"],
            ["city" => "Pratapgarh", "state" => "Rajasthan"],
            ["city" => "Rajsamand", "state" => "Rajasthan"],
            ["city" => "Sikar", "state" => "Rajasthan"],
            ["city" => "Sawai Madhopur", "state" => "Rajasthan"],
            ["city" => "Sirohi", "state" => "Rajasthan"],
            ["city" => "Tonk", "state" => "Rajasthan"],
            ["city" => "Udaipur", "state" => "Rajasthan"],
            ["city" => "East Sikkim", "state" => "Sikkim"],
            ["city" => "North Sikkim", "state" => "Sikkim"],
            ["city" => "South Sikkim", "state" => "Sikkim"],
            ["city" => "West Sikkim", "state" => "Sikkim"],
            ["city" => "Ariyalur", "state" => "Tamil Nadu"],
            ["city" => "Chennai", "state" => "Tamil Nadu"],
            ["city" => "Coimbatore", "state" => "Tamil Nadu"],
            ["city" => "Cuddalore", "state" => "Tamil Nadu"],
            ["city" => "Dharmapuri", "state" => "Tamil Nadu"],
            ["city" => "Dindigul", "state" => "Tamil Nadu"],
            ["city" => "Erode", "state" => "Tamil Nadu"],
            ["city" => "Kanchipuram", "state" => "Tamil Nadu"],
            ["city" => "Kanyakumari", "state" => "Tamil Nadu"],
            ["city" => "Karur", "state" => "Tamil Nadu"],
            ["city" => "Madurai", "state" => "Tamil Nadu"],
            ["city" => "Nagapattinam", "state" => "Tamil Nadu"],
            ["city" => "Nilgiris", "state" => "Tamil Nadu"],
            ["city" => "Namakkal", "state" => "Tamil Nadu"],
            ["city" => "Perambalur", "state" => "Tamil Nadu"],
            ["city" => "Pudukkottai", "state" => "Tamil Nadu"],
            ["city" => "Ramanathapuram", "state" => "Tamil Nadu"],
            ["city" => "Salem", "state" => "Tamil Nadu"],
            ["city" => "Sivaganga", "state" => "Tamil Nadu"],
            ["city" => "Tiruppur", "state" => "Tamil Nadu"],
            ["city" => "Tiruchirappalli", "state" => "Tamil Nadu"],
            ["city" => "Theni", "state" => "Tamil Nadu"],
            ["city" => "Tirunelveli", "state" => "Tamil Nadu"],
            ["city" => "Thanjavur", "state" => "Tamil Nadu"],
            ["city" => "Thoothukudi", "state" => "Tamil Nadu"],
            ["city" => "Thiruvallur", "state" => "Tamil Nadu"],
            ["city" => "Thiruvarur", "state" => "Tamil Nadu"],
            ["city" => "Tiruvannamalai", "state" => "Tamil Nadu"],
            ["city" => "Vellore", "state" => "Tamil Nadu"],
            ["city" => "Viluppuram", "state" => "Tamil Nadu"],
            ["city" => "Virudhunagar", "state" => "Tamil Nadu"],
            ["city" => "Dhalai", "state" => "Tripura"],
            ["city" => "North Tripura", "state" => "Tripura"],
            ["city" => "South Tripura", "state" => "Tripura"],
            ["city" => "West Tripura", "state" => "Tripura"],
            ["city" => "Agra", "state" => "Uttar Pradesh"],
            ["city" => "Allahabad", "state" => "Uttar Pradesh"],
            ["city" => "Aligarh", "state" => "Uttar Pradesh"],
            ["city" => "Ambedkar Nagar", "state" => "Uttar Pradesh"],
            ["city" => "Auraiya", "state" => "Uttar Pradesh"],
            ["city" => "Azamgarh", "state" => "Uttar Pradesh"],
            ["city" => "Barabanki", "state" => "Uttar Pradesh"],
            ["city" => "Budaun", "state" => "Uttar Pradesh"],
            ["city" => "Bagpat", "state" => "Uttar Pradesh"],
            ["city" => "Bahraich", "state" => "Uttar Pradesh"],
            ["city" => "Bijnor", "state" => "Uttar Pradesh"],
            ["city" => "Ballia", "state" => "Uttar Pradesh"],
            ["city" => "Banda", "state" => "Uttar Pradesh"],
            ["city" => "Balrampur", "state" => "Uttar Pradesh"],
            ["city" => "Bareilly", "state" => "Uttar Pradesh"],
            ["city" => "Basti", "state" => "Uttar Pradesh"],
            ["city" => "Bulandshahar", "state" => "Uttar Pradesh"],
            ["city" => "Chandauli", "state" => "Uttar Pradesh"],
            ["city" => "Chhatrapati Shahuji Maharaj Nagar", "state" => "Uttar Pradesh"],
            ["city" => "Chitrakoot", "state" => "Uttar Pradesh"],
            ["city" => "Deoria", "state" => "Uttar Pradesh"],
            ["city" => "Etah", "state" => "Uttar Pradesh"],
            ["city" => "Kanshi Ram Nagar", "state" => "Uttar Pradesh"],
            ["city" => "Etawah", "state" => "Uttar Pradesh"],
            ["city" => "Firozabad", "state" => "Uttar Pradesh"],
            ["city" => "Farrukhabad", "state" => "Uttar Pradesh"],
            ["city" => "Fatehpur", "state" => "Uttar Pradesh"],
            ["city" => "Faizabad", "state" => "Uttar Pradesh"],
            ["city" => "Gautam Buddha Nagar", "state" => "Uttar Pradesh"],
            ["city" => "Gonda", "state" => "Uttar Pradesh"],
            ["city" => "Ghazipur", "state" => "Uttar Pradesh"],
            ["city" => "Gorakhpur", "state" => "Uttar Pradesh"],
            ["city" => "Ghaziabad", "state" => "Uttar Pradesh"],
            ["city" => "Hamirpur", "state" => "Uttar Pradesh"],
            ["city" => "Hardoi", "state" => "Uttar Pradesh"],
            ["city" => "Mahamaya Nagar", "state" => "Uttar Pradesh"],
            ["city" => "Jhansi", "state" => "Uttar Pradesh"],
            ["city" => "Jalaun", "state" => "Uttar Pradesh"],
            ["city" => "Jyotiba Phule Nagar", "state" => "Uttar Pradesh"],
            ["city" => "Jaunpur District", "state" => "Uttar Pradesh"],
            ["city" => "Ramabai Nagar (Kanpur Dehat)", "state" => "Uttar Pradesh"],
            ["city" => "Kannauj", "state" => "Uttar Pradesh"],
            ["city" => "Kanpur Nagar", "state" => "Uttar Pradesh"],
            ["city" => "Kaushambi", "state" => "Uttar Pradesh"],
            ["city" => "Kushinagar", "state" => "Uttar Pradesh"],
            ["city" => "Lalitpur", "state" => "Uttar Pradesh"],
            ["city" => "Lakhimpur-Kheri", "state" => "Uttar Pradesh"],
            ["city" => "Lucknow", "state" => "Uttar Pradesh"],
            ["city" => "Mau", "state" => "Uttar Pradesh"],
            ["city" => "Meerut", "state" => "Uttar Pradesh"],
            ["city" => "Maharajganj", "state" => "Uttar Pradesh"],
            ["city" => "Mahoba", "state" => "Uttar Pradesh"],
            ["city" => "Mirzapur", "state" => "Uttar Pradesh"],
            ["city" => "Moradabad", "state" => "Uttar Pradesh"],
            ["city" => "Mainpuri", "state" => "Uttar Pradesh"],
            ["city" => "Mathura", "state" => "Uttar Pradesh"],
            ["city" => "Muzaffarnagar", "state" => "Uttar Pradesh"],
            ["city" => "Panchsheel Nagar district Hapur", "state" => "Uttar Pradesh"],
            ["city" => "Pilibhit", "state" => "Uttar Pradesh"],
            ["city" => "Pratapgarh", "state" => "Uttar Pradesh"],
            ["city" => "Rampur", "state" => "Uttar Pradesh"],
            ["city" => "Raebareli", "state" => "Uttar Pradesh"],
            ["city" => "Saharanpur", "state" => "Uttar Pradesh"],
            ["city" => "Sitapur", "state" => "Uttar Pradesh"],
            ["city" => "Shahjahanpur", "state" => "Uttar Pradesh"],
            ["city" => "Sant Kabir Nagar", "state" => "Uttar Pradesh"],
            ["city" => "Siddharthnagar", "state" => "Uttar Pradesh"],
            ["city" => "Sonbhadra", "state" => "Uttar Pradesh"],
            ["city" => "Sant Ravidas Nagar", "state" => "Uttar Pradesh"],
            ["city" => "Sultanpur", "state" => "Uttar Pradesh"],
            ["city" => "Shravasti", "state" => "Uttar Pradesh"],
            ["city" => "Unnao", "state" => "Uttar Pradesh"],
            ["city" => "Varanasi", "state" => "Uttar Pradesh"],
            ["city" => "Almoral", "state" => "Uttarakhand"],
            ["city" => "Bageshwar", "state" => "Uttarakhand"],
            ["city" => "Chamoli", "state" => "Uttarakhand"],
            ["city" => "Champawat", "state" => "Uttarakhand"],
            ["city" => "Dehradun", "state" => "Uttarakhand"],
            ["city" => "Haridwar", "state" => "Uttarakhand"],
            ["city" => "Nainital", "state" => "Uttarakhand"],
            ["city" => "Pauri Garhwal", "state" => "Uttarakhand"],
            ["city" => "Pithoragarh", "state" => "Uttarakhand"],
            ["city" => "Rudraprayag", "state" => "Uttarakhand"],
            ["city" => "Tehri Garhwal", "state" => "Uttarakhand"],
            ["city" => "Udham Singh Nagar", "state" => "Uttarakhand"],
            ["city" => "Uttarkashi", "state" => "Uttarakhand"],
            ["city" => "Birbhum", "state" => "West Bengal"],
            ["city" => "Bankura", "state" => "West Bengal"],
            ["city" => "Bardhaman", "state" => "West Bengal"],
            ["city" => "Darjeeling", "state" => "West Bengal"],
            ["city" => "Dakshin Dinajpur", "state" => "West Bengal"],
            ["city" => "Hooghly", "state" => "West Bengal"],
            ["city" => "Howrah", "state" => "West Bengal"],
            ["city" => "Jalpaiguri", "state" => "West Bengal"],
            ["city" => "Cooch Behar", "state" => "West Bengal"],
            ["city" => "Kolkata", "state" => "West Bengal"],
            ["city" => "Malda", "state" => "West Bengal"],
            ["city" => "Paschim Medinipur", "state" => "West Bengal"],
            ["city" => "Purba Medinipur", "state" => "West Bengal"],
            ["city" => "Murshidabad", "state" => "West Bengal"],
            ["city" => "Nadia", "state" => "West Bengal"],
            ["city" => "North 24 Parganas", "state" => "West Bengal"],
            ["city" => "South 24 Parganas", "state" => "West Bengal"],
            ["city" => "Purulia", "state" => "West Bengal"],
            ["city" => "Uttar Dinajpur", "state" => "West Bengal"],
            ["city" => "Guwahati", "state" => "Assam"]
        ];

        foreach ($arr as $key => $value)
        {
            $state = LocationMaster::firstOrCreate([
                "state" => $value['state'],
                "type" => "state"
            ]);
            $city = LocationMaster::firstOrCreate([
                "state_id" => $state->id,
                "city" => $value['city'],
                "type" => "city"
            ]);
        }
    }
}
