<?php

use Illuminate\Database\Seeder;
use App\Models\MigratingBranch;
use App\Models\Asset;
class MigratingBranchTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	$arrBranch = [
         'ANDHERI WEST',
         'BORIVALI WEST',
         'C B SAKINAKA',
         'C B VILLE PARLE',
         'CHANDAVARKAR LANE BRANCH (1169)',
         'CHEMBUR - 0553',
         'COMMEERCIAL BRANCH FORT',
         'COMMERCAIL BRANCH VILE PARLE',
         'COMMERCIAL BRANCH',
         'COMMERCIAL BRANCH FORT',
         'COMMERCIAL BRANCH FORT(31282)',
         'COMMERCIAL BRANCH GIRGAON(8599)',
         'COMMERCIAL BRANCH VILE PARLE',
         'COMMERCIAL VILE PARLE',
         'D N ROAD BRANCH(08599)',
         'DAHISAR BRANCH',
         'DIAMOND BRANCH',
         'DIAMOND GARDEN BR, CHEMBUR',
         'DIAMOND GARDEN BRANCH,CHEMBUR(13340)',
         'E - SBBJ, KALBADEI BRANCH',
         'EMPIRE HOUSE BR.',
         'e-SBBJ ANDHERI (E), MUMBAI',
         'e-SBBJ ANDHERI EAST MUMBAI 31659',
         'E-SBBJ ANDHERI(E), MUMBAI',
         'E-SBBJ CB LOWER PAREL BRANCH(31278)',
         'e-SBBJ KALBADEVE BRANCH',
         'e-SBBJ KALBADEVI BRANCH',
         'e-SBH',
         'e-SBH BALLARD ESTATE, MUMBAI',
         'E-SBH CHEMBUR BRANCH920408)',
         'e-SBH MALAD BRANCH (20733)',
         'E-SBP',
         'E-SBP ANAND NAGAR DAHISAR EAST',
         'E-SBP BANDRA BRANCH(50458)',
         'e-SBP DADAR ',
         'e-SBP GOREGAON WEST',
         'Esbp link ROAD MALAD WEST',
         'e-SBP, MALAD BRANCH',
         'e-SBT FORT MUMBAI',
         'E-SBT KANDIVALI BRANCH',
         'GOKULDHAM BRANCH (6055)',
         'GOREGAON EAST',
         'GOREGAON EAST (1975)',
         'GOREGAON EAST BRANCH',
         'GOREGAON MULND LINK ROAD BRANCH(13178)',
         'GOREGAON WEST',
         'GOREGAON WEST (1266)',
         'GORGAON MULUND LINK ROAD BRANCH',
         'HFB, BORIVALI',
         'IFB MALAD',
         'IFB MALAD WEST BRANCH(04760)',
         'J P ROAD ANDHERI WEST (12959)',
         'KALBADEVI BRANCH',
         'KANDIVALI IND ESTATE',
         'KANDIVALI INDUSTRIAL ESTATE (0566)',
         'M G ROAD BRANCH, KANDIVALI WEST',
         'MALAD WEST',
         'MAROL BRANCH (01594)',
         'MAROL BRANCH(05168)',
         'NARIMAN POINT',
         'NARIMAN POINT (E-SBH)',
         'PEDDAR ROAD BRANCH',
         'RA CKC ANDHERI',
         'SARB MUMBAI SAKINAKA BRANCH',
         'SBBJ - MALAD WEST',
         'SBI - HYDRABADH GOKULDHAM',
         'SBI - HYDRABADH MALAD',
         'SBI - HYDRABADH SANTACRUZ',
         'SBI - LBS KURLA',
         'SBI CHAKALA ROAD',
         'SBI SME DADAR BRANCH (04114)',
         'SIR P M ROAD',
         'SME BACKBAY RECLAMATION (11688)',
         'SME BACKBAY RECLAMATION (31278)',
         'SME BACKBAY RECLAMATION BRANCH',
         'SME BACKBAY RECLAMATION BRANCH (11688)',
         'SME BACKBAY RECLAMATION BRANCH(11688)',
         'SME GOREGAON BRANCH - 12521',
         'SME GOREGAON EAST BRANCH',
         'SME GOREGAON EAST BRANCH (12521)',
         'SME MIDC ANDHERI - 17879',
         'SME MIDC ANDHERI (E)',
         'SME MIDC ANDHERI BRANCH',
         'SME MIDC ANDHERI -E (17879)',
         'SME MIDC ANDHERI EAST(17879)',
         'SME MIDC, ANDHERI - 17879',
         'SME MIDC, ANDHERI EAST (17879)',
         'SMECC BORIVALI WEST(15521)',
         'TARDEO BRANCH - CODE - 18708',
         'TERNER ROAD BRANDRA',
         'TURNER ROAD, BANDRA',
         "Commercial Branch",
        "Sme Backbay Reclamation Branch",
        "Goregaon East Branch",
        "Diamond Branch",
        "Commercial Vile Parle",
        "Diamond Garden Branch,chembur(13340)",
        "E-sbp Bandra Branch(50458)",
        "Sme Goregaon East Branch (12521)",
        "Hfb, Borivali",
        "Commercial Branch Fort",
        "Kalbadevi Branch",
        "E-sbbj Kalbadeve Branch",
        "e-SBBJ Kalbadeve Branch",
        "Diamond Garden Br, Chembur",
        "Sme Goregaon East Branch",
        "Peddar Road Branch",
        "Nariman Point",
        "Sbi - Lbs Kurla",
        "Sbi - Hydrabadh Malad",
        "Sbi - Hydrabadh Santacruz",
        "E-sbh Malad Branch (20733)",
        "Sbi - Hydrabadh Gokuldham",
        "Dahisar Branch",
        "E-sbp Dadar",
        "E-sbp, Malad Branch",
        "Sbi Chakala Road",
        "M G Road Branch, Kandivali West",
        "E - Sbbj, Kalbadei Branch",
        "Tardeo Branch - Code - 18708",
        "Sme Midc, Andheri - 17879",
        "Ra Ckc Andheri",
        "E-sbbj Andheri East Mumbai 31659",
        "Malad West",
        "E-sbp Goregaon West",
        "Terner Road Brandra",
        "Chandavarkar Lane Branch (1169)",
        "Sbbj - Malad West",
        "Goregaon West",
        "Gokuldham Branch (6055)",
        "E-sbp",
        "E-sbt Fort Mumbai",
        "E-sbh",
        "Goregaon West (1266)",
        "Esbp Link Road Malad West",
        "Sme Backbay Reclamation Branch (11688)",
        "E-sbp  Bandra Branch(50458)",
        "E-sbbj Cb Lower Parel Branch(31278)",
        "Chembur - 0553",
        "Commercial Branch Fort(31282)",
        "D N Road Branch(08599)",
        "E-sbh Chembur Branch920408)",
        "E-sbh Chembur Branch (920408)",
        "Goregaon East (1975)",
        "Commercial Branch Girgaon(8599)",
        "Marol Branch(05168)",
        "E-sbp Anand Nagar Dahisar East",
        "IFB Malad",
        "E-sbt Kandivali Branch",
        "e-SBBJ Kalbadevi Branch",
        "Sme Midc Andheri (E)",
        "Sme Midc Andheri -E (17879)",
        "Ifb Malad West Branch(04760)",
        "Sme Backbay Reclamation (11688)",
        "Sarb Mumbai Sakinaka Branch",
        "Marol Branch (01594)",
        "Commercial Branch Vile Parle",
        "E-sbbj Andheri (E), Mumbai",
        "C B Sakinaka",
        "e-SBT Fort Mumbai",
        "Gorgaon Mulund Link Road Branch",
        "E-sbbj Andheri(e), Mumbai",
        "Turner Road, Bandra",
        "Commercail Branch Vile Parle",
        "Sme Backbay Reclamation Branch(11688)",
        "COMMERCIAL BRANCH GIRGAON(8599)",
        "e-SBP DADAR",
        "SBI SME DADAR BRANCH (04114)",
        "E-sbh Ballard Estate, Mumbai",
        "Kandivali Ind Estate",
        "Empire House Br.",
        "Sme Midc Andheri Branch",
        "Sme Backbay Reclamation (31278)",
        "Smecc Borivali West(15521)",
        "Goregaon East",
        "Sir P M Road",
        "Sme Midc, Andheri East (17879)",
        "J P Road Andheri West (12959)",
        "Sme Goregaon Branch - 12521",
        "Kandivali Industrial Estate (0566)",
        "Diamond Garden Branch ,chembur(13340)",
        "Dosar Bhawan Chowk Branch (e-SBP)",
        "E- Sbh",
        "E- State Patiala (SBP) Kandivali East Br. (51014)",
        "E-sbh Chembur Branch(920408)",
        "E-sbp  Bandra Branch(50458)",
        "E-sbp Dadar",
        "e-SBT CORPORATE FINANCE BRANCH, MUMBAI - 70666",
        "Nariman Point Branch 6945",
        "SAMB II,MUMBAI",
        "SME MIDC ANDHERI, MUMBAI (17879)",
        "Vashi Turbhe Branch (03736)",
      ];
    $arrBranch = array_map("strtoupper",$arrBranch);
    $arrBranch = array_unique($arrBranch);
      foreach ($arrBranch as $key => $value)
      {
        //$branch_name = strtoupper($value);
        
        $branch = MigratingBranch::updateOrCreate(['name'=>$value]);

        if(!is_null($branch))
        {
            
        }else{
            /*$existing_branch = MigratingBranch::where('LOWER(name)','LIKE','%'.strtolower($value).'%')->first();
            if(!is_null($existing_branch))
            {
                dd($existing_branch);
                $destroy = $existing_branch->delete($existing_branch);
                $asset = Asset::where('customer.migrating_branch','LIKE','%'.$existing_branch->id.'%')->first();
                if(!is_null($asset))
                {
                    $asset->update(['customer.migrating_branch'=>$branch->id]);
                }
            }*/
        }
        

      }
    }
}
